const ACTIVITY_STORAGE_KEY = '@activities';
const APP_STATE_CHANGED_TIMESTAMP_STORAGE_KEY = '@appStateChangedTimestamp';
const TIME_STORAGE_KEY = '@time';
const IS_PAUSED_STORAGE_KEY = '@isPaused';

export {
  ACTIVITY_STORAGE_KEY,
  APP_STATE_CHANGED_TIMESTAMP_STORAGE_KEY,
  TIME_STORAGE_KEY,
  IS_PAUSED_STORAGE_KEY,
};
